# Make datasets for data visualisation using Vega-Lite

In [2]:
import pandas as pd

## 1. Histogram of Player Age

In [3]:
stats_22_df = pd.read_csv("../datasets/Big5/2021-2022/stats.csv")

In [4]:
stats_22_df.head()

,Player,Nation,Pos,Squad,Comp,Age,Born,Playing Time MP,Playing Time Starts,Playing Time Min,...,Per 90 Minutes G+A-PK,Expected xG,Expected npxG,Expected xA,Expected npxG+xA,Per 90 Minutes xG,Per 90 Minutes xA,Per 90 Minutes xG+xA,Per 90 Minutes npxG,Per 90 Minutes npxG+xA
0,Max Aarons,ENG,DF,Norwich City,Premier League,21.0,2000.0,34,32,2881,...,0.06,0.7,0.7,1.4,2.1,0.02,0.04,0.06,0.02,0.06
1,Yunis Abdelhamid,MAR,DF,Reims,Ligue 1,33.0,1987.0,34,34,2983,...,0.06,1.2,1.2,0.8,2.1,0.04,0.02,0.06,0.04,0.06
2,Salis Abdul Samed,GHA,MF,Clermont Foot,Ligue 1,21.0,2000.0,31,29,2462,...,0.04,0.8,0.8,1.1,1.9,0.03,0.04,0.07,0.03,0.07
3,Laurent Abergel,FRA,MF,Lorient,Ligue 1,28.0,1993.0,34,34,2956,...,0.06,2.0,2.0,2.9,4.9,0.06,0.09,0.15,0.06,0.15
4,Charles Abi,FRA,FW,Saint-Étienne,Ligue 1,21.0,2000.0,1,1,45,...,0.00,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00

In [10]:
stats_22_df[stats_22_df.isnull().any(axis=1)]

,Player,Nation,Pos,Squad,Comp,Age,Born,Playing Time MP,Playing Time Starts,Playing Time Min,...,Per 90 Minutes G+A-PK,Expected xG,Expected npxG,Expected xA,Expected npxG+xA,Per 90 Minutes xG,Per 90 Minutes xA,Per 90 Minutes xG+xA,Per 90 Minutes npxG,Per 90 Minutes npxG+xA
1531,Javier Llabrés,NaN,FW,Mallorca,La Liga,NaN,NaN,5,1,132,...,0.0,0.1,0.1,0.1,0.2,0.1,0.05,0.15,0.1,0.15

In [16]:
stats_22_df.at[1531, 'Age'] = 18 # age as of 1 Aug 2021
stats_22_df.at[1531, 'Born'] = 2002

In [17]:
stats_22_df[stats_22_df.isnull().any(axis=1)] # set Llabres age to 18

,Player,Nation,Pos,Squad,Comp,Age,Born,Playing Time MP,Playing Time Starts,Playing Time Min,...,Per 90 Minutes G+A-PK,Expected xG,Expected npxG,Expected xA,Expected npxG+xA,Per 90 Minutes xG,Per 90 Minutes xA,Per 90 Minutes xG+xA,Per 90 Minutes npxG,Per 90 Minutes npxG+xA
1531,Javier Llabrés,NaN,FW,Mallorca,La Liga,18.0,2002.0,5,1,132,...,0.0,0.1,0.1,0.1,0.2,0.1,0.05,0.15,0.1,0.15

In [32]:
df1 = stats_22_df[['Comp', 'Age']]

In [33]:
temp = df1['Age'].astype('int')
df1.loc[:, ['Age']] = temp

In [43]:
df1_by_comp_age = df1.groupby(['Comp', 'Age']).size().reset_index().rename(columns={0:'Count'})

In [46]:
df1.value_counts().reset_index()

           Comp  Age   0
0       Serie A   26  55
1    Bundesliga   23  54
2       Ligue 1   24  53
3       La Liga   29  52
4       Ligue 1   23  52
..          ...  ...  ..
116     La Liga   40   1
117     La Liga   37   1
118  Bundesliga   37   1
119  Bundesliga   36   1
120     Serie A   40   1

[121 rows x 3 columns]

## 2. First Choice Goalkeeper Dataset (2021/2022 season)

In [3]:
team_standings_df = pd.read_csv('../vis_data/team standings 2021-2022.csv')

In [4]:
team_standings_df.head()

,Squad,Country,LgRk,MP,W,D,L,GF,GA,GD,Pts,Pts/MP,xG,xGA,xGD,xGD/90,Attendance,Top Team Scorer,Goalkeeper
0,Manchester City,eng ENG,1,38,29,6,3,99,26,73,93,2.45,88.5,27.1,61.3,1.61,52774,Kevin De Bruyne - 15,Ederson
1,Liverpool,eng ENG,2,38,28,8,2,94,26,68,92,2.42,89.2,33.8,55.4,1.46,53352,Mohamed Salah - 23,Alisson
2,Bayern Munich,de GER,1,34,24,5,5,97,37,60,77,2.26,88.1,37.1,51.0,1.50,33176,Robert Lewandowski - 35,Manuel Neuer
3,Paris S-G,fr FRA,1,38,26,8,4,90,36,54,86,2.26,76.5,38.6,37.9,1.00,41589,Kylian Mbappé - 28,Keylor Navas
4,Real Madrid,es ESP,1,38,26,8,4,80,31,49,86,2.26,74.4,46.8,27.6,0.73,41235,Karim Benzema - 27,Thibaut Courtois

In [7]:
team_standings_df.shape

(98, 19)

In [5]:
keepers_df = pd.read_csv('../datasets/Big5/2021-2022/keepers.csv')
keepers_df.head()

,Player,Nation,Pos,Squad,Comp,Age,Born,Playing Time MP,Playing Time Starts,Playing Time Min,...,Performance W,Performance D,Performance L,Performance CS,Performance CS%,Penalty Kicks PKatt,Penalty Kicks PKA,Penalty Kicks PKsv,Penalty Kicks PKm,Penalty Kicks Save%
0,Julen Agirrezabala,ESP,GK,Athletic Club,La Liga,20,2000,4,4,360,...,1,2,1,1,25.0,0,0,0,0,NaN
1,Doğan Alemdar,TUR,GK,Rennes,Ligue 1,18,2002,12,12,1080,...,6,1,5,4,33.3,2,1,1,0,50.0
2,Alisson,BRA,GK,Liverpool,Premier League,28,1992,36,36,3240,...,27,7,2,20,55.6,0,0,0,0,NaN
3,Alphonse Areola,FRA,GK,West Ham,Premier League,28,1993,1,1,90,...,0,0,1,0,0.0,0,0,0,0,NaN
4,Kepa Arrizabalaga,ESP,GK,Chelsea,Premier League,26,1994,4,4,360,...,2,1,1,2,50.0,0,0,0,0,NaN

In [6]:
keepers_adv_df = pd.read_csv('../datasets/Big5/2021-2022/keepersadv.csv')
keepers_adv_df.head()

,Player,Nation,Pos,Squad,Comp,Age,Born,90s,Goals GA,Goals PKA,...,Passes AvgLen,Goal Kicks Att,Goal Kicks Launch%,Goal Kicks AvgLen,Crosses Opp,Crosses Stp,Crosses Stp%,Sweeper #OPA,Sweeper #OPA/90,Sweeper AvgDist
0,Julen Agirrezabala,ESP,GK,Athletic Club,La Liga,20,2000,4.0,5,0,...,36.8,26,38.5,38.3,35,2,5.7,5,1.25,17.3
1,Doğan Alemdar,TUR,GK,Rennes,Ligue 1,18,2002,12.0,13,1,...,33.5,70,84.3,57.7,108,5,4.6,14,1.17,15.2
2,Alisson,BRA,GK,Liverpool,Premier League,28,1992,36.0,24,0,...,29.9,171,45.6,40.0,221,21,9.5,63,1.75,18.1
3,Alphonse Areola,FRA,GK,West Ham,Premier League,28,1993,1.0,1,0,...,49.7,14,71.4,53.2,13,1,7.7,0,0.00,7.0
4,Kepa Arrizabalaga,ESP,GK,Chelsea,Premier League,26,1994,4.0,2,0,...,30.8,21,28.6,30.2,31,1,3.2,5,1.25,16.2

In [15]:
# merge team standings with standard goalkeeper stats dataset on goalkeeper and squad
temp_df = team_standings_df.merge(keepers_df, left_on=["Squad", "Goalkeeper"], right_on=["Squad", "Player"])

In [21]:
final_df = temp_df.merge(keepers_adv_df, left_on=["Squad", "Goalkeeper"], right_on=["Squad", "Player"])

In [22]:
final_df.head()

,Squad,Country,LgRk,MP,W,D,L,GF,GA,GD,...,Passes AvgLen,Goal Kicks Att,Goal Kicks Launch%,Goal Kicks AvgLen,Crosses Opp,Crosses Stp,Crosses Stp%,Sweeper #OPA,Sweeper #OPA/90,Sweeper AvgDist
0,Manchester City,eng ENG,1,38,29,6,3,99,26,73,...,30.0,138,24.6,31.6,181,16,8.8,34,0.92,17.2
1,Liverpool,eng ENG,2,38,28,8,2,94,26,68,...,29.9,171,45.6,40.0,221,21,9.5,63,1.75,18.1
2,Bayern Munich,de GER,1,34,24,5,5,97,37,60,...,30.7,166,14.5,27.5,191,12,6.3,41,1.47,19.8
3,Paris S-G,fr FRA,1,38,26,8,4,90,36,54,...,27.0,139,11.5,22.4,155,8,5.2,11,0.53,13.4
4,Real Madrid,es ESP,1,38,26,8,4,80,31,49,...,31.2,210,41.9,39.1,312,27,8.7,21,0.58,14.2

In [23]:
final_df.columns

Index(['Squad', 'Country', 'LgRk', 'MP', 'W', 'D', 'L', 'GF', 'GA', 'GD',
       'Pts', 'Pts/MP', 'xG', 'xGA', 'xGD', 'xGD/90', 'Attendance',
       'Top Team Scorer', 'Goalkeeper', 'Player_x', 'Nation_x', 'Pos_x',
       'Comp_x', 'Age_x', 'Born_x', 'Playing Time MP', 'Playing Time Starts',
       'Playing Time Min', 'Playing Time 90s', 'Performance GA',
       'Performance GA90', 'Performance SoTA', 'Performance Saves',
       'Performance Save%', 'Performance W', 'Performance D', 'Performance L',
       'Performance CS', 'Performance CS%', 'Penalty Kicks PKatt',
       'Penalty Kicks PKA', 'Penalty Kicks PKsv', 'Penalty Kicks PKm',
       'Penalty Kicks Save%', 'Player_y', 'Nation_y', 'Pos_y', 'Comp_y',
       'Age_y', 'Born_y', '90s', 'Goals GA', 'Goals PKA', 'Goals FK',
       'Goals CK', 'Goals OG', 'Expected PSxG', 'Expected PSxG/SoT',
       'Expected PSxG+/-', 'Expected /90', 'Launched Cmp', 'Launched Att',
       'Launched Cmp%', 'Passes Att', 'Passes Thr', 'Passes Launch%',
       'Passes AvgLen', 'Goal Kicks Att', 'Goal Kicks Launch%',
       'Goal Kicks AvgLen', 'Crosses Opp', 'Crosses Stp', 'Crosses Stp%',
       'Sweeper #OPA', 'Sweeper #OPA/90', 'Sweeper AvgDist'],
      dtype='object')

In [26]:
final_df = final_df.drop(columns=['Country', 'Player_y', 'Nation_y', 'Pos_y', 'Comp_y', 'Age_y', 'Born_y', '90s', 'Goals GA', 'Performance W', 'Performance D', 'Performance L'])

In [30]:
final_df = final_df.rename(columns={'Player_x': 'Player', 'Nation_x':'Nation', 'Pos_x': 'Pos', 'Comp_x': 'Comp', 'Age_x': 'Age', 'Born_x': 'Born'})

In [31]:
final_df.to_csv('../vis_data/gk_and_team_standings.csv', index=False)